{% set name = "q" %}
{% set version = "3.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Sann5/q/archive/pack_issue_326.zip
  sha256: 2ebf1804abd7d35d067f799282f3b1fa653c93f05871eabc0fa382605770a31f

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [win]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six

test:
  imports:
    - bin
  requires:
    #- pip
    - pytest
    - which
  commands:
    #- pip check
    - q -h
    - export Q_EXECUTABLE="$(which q)"
    - export Q_SKIP_EXECUTABLE_VALIDATION="true"
    - export Q_DEBUG=true
    - pytest -k 'not octosql_matrix and not textql_matrix and not q_matrix' --pyargs bin

about:
  home: https://github.com/harelba/q
  summary: 'Run SQL directly on delimited files and multi-file sqlite databases'
  description: |
    q's purpose is to bring SQL expressive power to the Linux command line and to provide easy access to text as actual data. It allows 1)
    performing SQL-like statements directly on tabular text data, auto-caching the data in order to accelerate additional querying on the same file, and 2)
    performing SQL statements directly on multi-file sqlite3 databases, without having to merge them or load them into memory.
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  doc_url: https://harelba.github.io/q/
  dev_url: https://github.com/harelba/q

extra:
  recipe-maintainers:
    - Sann5
